Use active record 7.2 and fix booting up tests
Using ActiveRecord::VERSION = 7.2.2.1
Established connection using {:adapter=>"postgresql", :database=>"arjdbc_test", :host=>"localhost", :username=>"arjdbc", :password=>"arjdbc", :connect_timeout=>10, :encoding=>"utf8", :collate=>"en_US.UTF-8"}
ArgumentError: wrong number of arguments (given 2, expected 1)
               serialize at /home/jessec/.gem/jruby/3.1.4/gems/activerecord-7.2.2.1/lib/active_record/attribute_methods/serialization.rb:184
  <class:ImportantTopic> at /home/jessec/bryk/vendor_gems/activerecord-jdbc-adapter/test/models/topic.rb:6
                  <main> at /home/jessec/bryk/vendor_gems/activerecord-jdbc-adapter/test/models/topic.rb:5
                 require at org/jruby/RubyKernel.java:1187
                  <main> at /home/jessec/bryk/vendor_gems/activerecord-jdbc-adapter/test/bind_params_length_test.rb:2
                 require at org/jruby/RubyKernel.java:1187
                  <main> at /home/jessec/bryk/vendor_gems/activerecord-jdbc-adapter/test/db/postgresql/bind_params_length_test.rb:2
                 require at org/jruby/RubyKernel.java:1187
                  <main> at /home/jessec/.gem/jruby/3.1.4/gems/rake-13.2.1/lib/rake/rake_test_loader.rb:21
                  select at org/jruby/RubyArray.java:2882
                  <main> at /home/jessec/.gem/jruby/3.1.4/gems/rake-13.2.1/lib/rake/rake_test_loader.rb:6