probably best to not realy on OID from AR itself (until it's made shareable by core)
... avoid possible :
ArgumentError: A copy of ActiveRecord::ConnectionAdapters::PostgreSQLAdapter::OID has been removed from the module tree but is still active!